---
# configuration for GitHub Actions
name: dd tests
on:
    push:
    pull_request:
    schedule:
        - cron: '37 5 5 * *'
jobs:
    build:
        name: Build
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                python-version: [
                    '3.11',
                    ]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Prepare installation environment
              run: |
                ./.github/workflows/setup_build_env.sh
            - name: Install `dd`
              run: |
                set -o posix
                echo "Exported environment variables:"
                export -p
                python setup.py install --fetch --cudd --cudd_zdd --sylvan
            - name: Install test dependencies
              run: |
                pip install pytest
            - name: Run `dd` tests
              run: |
                set -o posix
                echo "Exported environment variables:"
                export -p
                # run tests
                make test
